--max_temp
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION max_temp_ANOMMODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TRAIN_80_00'),
  TIMESTAMP_COLNAME => 'DATE_F',
  TARGET_COLNAME => 'max_temp',
  LABEL_COLNAME => '');

BEGIN 
    CALL max_temp_ANOMMODEL!DETECT_ANOMALIES(
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TEST_00_20'),
        TIMESTAMP_COLNAME => 'DATE_F',
        TARGET_COLNAME => 'max_temp');
    LET x := SQLID;
    CREATE OR REPLACE TABLE max_temp_ANOMS AS SELECT * FROM TABLE(RESULT_SCAN(:x));
END;

--mean_temp
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION mean_temp_ANOMMODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TRAIN_80_00'),
  TIMESTAMP_COLNAME => 'DATE_F',
  TARGET_COLNAME => 'mean_temp',
  LABEL_COLNAME => '');

BEGIN 
    CALL mean_temp_ANOMMODEL!DETECT_ANOMALIES(
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TEST_00_20'),
        TIMESTAMP_COLNAME => 'DATE_F',
        TARGET_COLNAME => 'mean_temp');
    LET x := SQLID;
    CREATE OR REPLACE TABLE mean_temp_ANOMS AS SELECT * FROM TABLE(RESULT_SCAN(:x));
END;

--min_temp
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION min_temp_ANOMMODEL(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TRAIN_80_00'),
  TIMESTAMP_COLNAME => 'DATE_F',
  TARGET_COLNAME => 'min_temp',
  LABEL_COLNAME => '');

BEGIN 
    CALL min_temp_ANOMMODEL!DETECT_ANOMALIES(
        INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'TEST_00_20'),
        TIMESTAMP_COLNAME => 'DATE_F',
        TARGET_COLNAME => 'min_temp');
    LET x := SQLID;
    CREATE OR REPLACE TABLE min_temp_ANOMS AS SELECT * FROM TABLE(RESULT_SCAN(:x));
END;

SELECT * FROM min_temp_ANOMS where IS_ANOMALY;
